name: shamsi_date
description: >
  A Flutter and Dart package for using Jalali (Shamsi, Solar, Persian, Jalaali or شمسی) calendar.
  You can convert, format and manipulate Jalali and Gregorian (Miladi) date and times.
repository: https://github.com/FatulM/shamsi_date
homepage: https://github.com/FatulM/shamsi_date

version: 1.0.4

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.0.0
